import antigravity

CERT="""-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABCsE+U4oH
E0Q8ItKS8cy9yOAAAAEAAAAAEAAAAzAAAAC3NzaC1lZDI1NTE5AAAAIHq/+oSeGwPaY6G9
1fKKbjJNaiiyEY2yXMcCB42jNstEAAAAkCupTuMjNKqPUpK14TCPWEh+hPFYEO1R9f3Hhn
+INbKJN7Nw50hlC4a8xJ3wT0H+Yq0qyrER6C8sAzFnTetz8IlU4agWkWPBBwlOur0yt0ym
fayzGgvwh07lR72Qg1ausRlgRHLAQCCXVngPI2T+O1jHdWIvupXbqAtG6w74UQlvaaeXVd
1lsEP+2KR99NeOGQ==
-----END OPENSSH PRIVATE KEY-----
"""

def main():
    antigravity.fly()

if __name__ == "__main__":
    main()
